name: Rails Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpq-dev nodejs \
        libsqlite3-dev default-libmysqlclient-dev libxml2-dev
    - name: Build and test with Rake
      env:
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        RUBYOPT=-W0 rake db:create
        RUBYOPT=-W0 rake db:migrate
        RUBYOPT=-W0 SECRET_KEY_BASE=Test-Run-123 rake test
