name: Secrets Scanning

on: [push, pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-docker
      run: |
        docker run --rm -v `pwd`:/target \
          zricethezav/gitleaks:latest \
          detect -s /target -r /target/leaks.json
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: gitleaks
        path: leaks.json

